# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Le blog de Raph
tagline:          ''
description:      ''
url:              http://www.raphael-brugier.fr/
baseurl:          /

permalink:    /posts/:title/

author:
  name:           'Raphaël Brugier'
  url:            https://twitter.com/rbrugier

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde

gems:
  - jekyll-redirect-from
  - jekyll-sitemap