baseurl = "http://raphaelbrugier.github.io/"
title = "Raphael Brugier"
languageCode = "en-us"

[params]
  viewMorePostLink = "/blog/"

[[params.menu]]
  name = "About"
  url  = "/about/"
  weight = 3

[params.recent_posts]
  enable = true

[params.widgets]
    categories = true
    tags = true
    search = true