baseurl = "http://raphaelbrugier.github.io/"
title = "Raphael Brugier"
languageCode = "en-us"
googleAnalytics = "UA-3393491-2"
disqusShortname = "raphaelbrugierblog"

[params]
  viewMorePostLink = "/blog/"

[[params.menu]]
  name = "About"
  url  = "/about/"
  weight = 3

[[params.social]]
  name = "twitter"
  url  = "https://twitter.com/rbrugier"
  weight = 1
[[params.social]]
  name = "linkedin"
  url  = "https://www.linkedin.com/in/raphaelbrugier"
  weight = 2
[[params.social]]
  name = "github"
  url  = "https://github.com/RaphaelBrugier"
  weight = 3

[params.recent_posts]
  enable = true

[params.widgets]
    categories = true
    tags = true
    search = true