baseurl = "http://raphaelbrugier.github.io/"
title = "Raphael Brugier's blog"
languageCode = "en-us"


[[params.menu]]
    name = "Blog"
    url  = "/blog/"
    weight = 2

[params.recent_posts]
    enable = true
